---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-native-postgres
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: spring-native-postgres
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-native-postgres
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-native-postgres
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: spring-native-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-native-postgres
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-08-23 - 19:43:05 +0000
      labels:
        app.kubernetes.io/name: spring-native-postgres
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: spring.datasource.url
              value: "Hello from the environment"
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: sarvangeeks/spring-native-postgres:latest
          imagePullPolicy: Always
          name: spring-native-postgres
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: sarvandockerhub
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: spring-native-postgres
  namespace: quarkuspoc-dev
  labels:
    app.kubernetes.io/name: spring-native-postgres
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  path: /
  to:
    kind: Service
    name: spring-native-postgres
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
