FROM ghcr.io/graalvm/native-image:ol8-java17-22 AS builder

RUN microdnf update -y && \
microdnf install -y maven gcc glibc-devel zlib-devel libstdc++-devel gcc-c++ && \
microdnf clean all \

WORKDIR /build
COPY pom.xml /build/
COPY src /build/src

# Build
RUN mvn package -Pnative

# The deployment Image
FROM docker.io/oraclelinux:8-slim
EXPOSE 8080
# Copy the native executable into the containers
COPY --from=builder /build/target/springnative .
ENTRYPOINT ["/springnative"]