FROM ghcr.io/graalvm/native-image:ol8-java17-22 AS build

WORKDIR /build
COPY mvnw /build/
COPY .mvn /build/mvn
COPY pom.xml /build/
COPY src /build/src

# Build
RUN chmod 777 mvnw
RUN ./mvnw package -Pnative -DskipTests=true

# The deployment Image
FROM docker.io/alpine
EXPOSE 8080
# Copy the native executable into the containers
COPY --from=build /build/target/springnative .
ENTRYPOINT ["/springnative"]